### ISSUE TITLE
search bug

### ISSUE THREAD

**Issue by GordonKing** [FWdarling/DistributedHw2#1]
当我跑SERVER 的时候 返回为0或者其他数字时候 无法用Integer.parse 成功 是否有过？是17个字的问题么？

**Comment by FWdarling** [comment]
请问一下是哪个server呢？ 因为项目是先做数据切分而后做查找，查询服务器也是数据切分的客户端， 我不知道您说的是哪个server

**Comment by FWdarling** [comment]
确实是代码的问题， 忘记给抽象类map实例化一个子类了， 并且多线程lock写的也有问题，现已修复。
（ps： 现在的代码是本地测试环境， 可根据需要自行修改）
